'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AssessmentCriterion
    Public Property Id As Integer
    Public Property CalculationFilterId As Integer
    Public Property AssessmentCriterionGroupId As Integer
    Public Property ThresholdRangeLower As Double
    Public Property ThresholdRangeUpper As Double
    Public Property ThresholdTypeId As Integer
    Public Property RoundingDecimalPlaces As Integer
    Public Property MonitorLocationId As Integer
    Public Property CriterionIndex As Integer
    Public Property PlotAssessedLevel As Boolean
    Public Property AssessedLevelSeriesName As String = ""
    Public Property AssessedLevelDashStyleId As Integer
    Public Property AssessedLevelLineWidth As Integer
    Public Property AssessedLevelLineColour As String
    Public Property AssessedLevelSeriesTypeId As Integer
    Public Property AssessedLevelMarkersOn As Boolean
    Public Property PlotCriterionLevel As Boolean
    Public Property CriterionLevelSeriesName As String = ""
    Public Property CriterionLevelDashStyleId As Integer
    Public Property CriterionLevelLineWidth As Integer
    Public Property CriterionLevelLineColour As String
    Public Property TabulateAssessedLevels As Boolean
    Public Property MergeAssessedLevels As Boolean
    Public Property AssessedLevelHeader1 As String = ""
    Public Property AssessedLevelHeader2 As String = ""
    Public Property AssessedLevelHeader3 As String = ""
    Public Property TabulateCriterionTriggers As Boolean
    Public Property MergeCriterionTriggers As Boolean
    Public Property CriterionTriggerHeader1 As String = ""
    Public Property CriterionTriggerHeader2 As String = ""
    Public Property CriterionTriggerHeader3 As String = ""

    Public Overridable Property CalculationFilter As CalculationFilter
    Public Overridable Property AssessmentCriterionGroup As AssessmentCriterionGroup
    Public Overridable Property MonitorLocation As MonitorLocation
    Public Overridable Property ThresholdType As ThresholdType
    Public Overridable Property AssessedLevelDashStyle As SeriesDashStyle
    Public Overridable Property AssessedLevelSeriesType As MeasurementViewSeriesType
    Public Overridable Property CriterionLevelDashStyle As SeriesDashStyle

End Class
