'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AssessmentCriterionGroup
    Public Property Id As Integer
    Public Property GroupName As String
    Public Property ProjectId As Integer
    Public Property MeasurementTypeId As Integer
    Public Property ThresholdAggregateDurationId As Integer
    Public Property AssessmentPeriodDurationTypeId As Integer
    Public Property AssessmentPeriodDurationCount As Integer
    Public Property ShowGraph As Boolean
    Public Property GraphTitle As String = ""
    Public Property GraphYAxisMin As Double
    Public Property GraphYAxisMax As Double
    Public Property GraphXAxisLabel As String = ""
    Public Property GraphYAxisLabel As String = ""
    Public Property GraphYAxisTickInterval As Double
    Public Property NumDateColumns As Integer
    Public Property DateColumn1Header As String = ""
    Public Property DateColumn1Format As String = ""
    Public Property DateColumn2Header As String = ""
    Public Property DateColumn2Format As String = ""
    Public Property MergeHeaderRow1 As Boolean
    Public Property MergeHeaderRow2 As Boolean
    Public Property MergeHeaderRow3 As Boolean
    Public Property ShowIndividualResults As Boolean
    Public Property SumExceedancesAcrossCriteria As Boolean
    Public Property SumPeriodExceedances As Boolean
    Public Property SumDaysWithExceedances As Boolean
    Public Property SumDailyEvents As Boolean
    Public Property ShowSumTitles As Boolean

    Public Overridable Property AssessmentCriteria As ICollection(Of AssessmentCriterion) = New HashSet(Of AssessmentCriterion)
    Public Overridable Property Project As Project
    Public Overridable Property ThresholdAggregateDuration As ThresholdAggregateDuration
    Public Overridable Property AssessmentPeriodDurationType As AssessmentPeriodDurationType
    Public Overridable Property MeasurementType As MeasurementType
    Public Overridable Property ExcludingMeasurementCommentTypes As ICollection(Of MeasurementCommentType) = New HashSet(Of MeasurementCommentType)

End Class
