'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CalculationFilter
    Public Property Id As Integer
    Public Property FilterName As String
    Public Property MeasurementMetricId As Integer
    Public Property InputMultiplier As String
    Public Property CalculationAggregateFunctionId As Integer
    Public Property TimeBase As Double
    Public Property UseTimeWindow As Boolean
    Public Property TimeWindowStartTime As Date
    Public Property TimeWindowEndTime As Date
    Public Property TimeStep As Double

    Public Overridable Property ApplicableDaysOfWeek As ICollection(Of DayOfWeek) = New HashSet(Of DayOfWeek)
    Public Overridable Property CalculationAggregateFunction As CalculationAggregateFunction
    Public Overridable Property MeasurementMetric As MeasurementMetric
    Public Overridable Property MeasurementViewSequenceSettings As ICollection(Of MeasurementViewSequenceSetting) = New HashSet(Of MeasurementViewSequenceSetting)
    Public Overridable Property AssessmentCriteria As ICollection(Of AssessmentCriterion) = New HashSet(Of AssessmentCriterion)

End Class
