'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contact
    Public Property Id As Integer
    Public Property ContactName As String
    Public Property SecureLoginId As Nullable(Of Integer)
    Public Property EmailAddress As String
    Public Property PrimaryTelephoneNumber As String
    Public Property SecondaryTelephoneNumber As String
    Public Property OrganisationId As Integer


    Public Overridable Property Organisation As Organisation
    Public Overridable Property Projects As ICollection(Of Project) = New HashSet(Of Project)
    Public Overridable Property ExcludedDocuments As ICollection(Of Document) = New HashSet(Of Document)
    Public Overridable Property UploadedMeasurements As ICollection(Of Measurement) = New HashSet(Of Measurement)
    Public Overridable Property MeasurementFiles As ICollection(Of MeasurementFile) = New HashSet(Of MeasurementFile)
    Public Overridable Property User As User
    Public Overridable Property MeasurementComments As ICollection(Of MeasurementComment) = New HashSet(Of MeasurementComment)

End Class
