'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Document
    Public Property Id As Integer
    Public Property Title As String
    Public Property HasDateRange As Boolean
    Public Property StartDateTime As Date
    Public Property EndDateTime As Date
    Public Property FilePath As String
    Public Property DocumentTypeId As Integer
    Public Property AuthorOrganisationId As Integer


    Public Overridable Property DocumentType As DocumentType
    Public Overridable Property AuthorOrganisation As Organisation
    Public Overridable Property Monitors As ICollection(Of Monitor) = New HashSet(Of Monitor)
    Public Overridable Property ExcludedContacts As ICollection(Of Contact) = New HashSet(Of Contact)
    Public Overridable Property MonitorLocations As ICollection(Of MonitorLocation) = New HashSet(Of MonitorLocation)
    Public Overridable Property Projects As ICollection(Of Project) = New HashSet(Of Project)

End Class
