'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MeasurementMetric
    Public Property Id As Integer
    Public Property MetricName As String
    Public Property DisplayName As String
    Public Property MeasurementTypeId As Integer
    Public Property FundamentalUnit As String
    Public Property RoundingDecimalPlaces As Integer

    Public Overridable Property MeasurementType As MeasurementType
    Public Overridable Property Measurements As ICollection(Of Measurement) = New HashSet(Of Measurement)
    Public Overridable Property CalculationFilters As ICollection(Of CalculationFilter) = New HashSet(Of CalculationFilter)

End Class
