'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MeasurementViewSequenceSetting
    Public Property Id As Integer
    Public Property SequenceIndex As Integer
    Public Property TableHeader As String
    Public Property SeriesName As String
    Public Property DayViewSeriesTypeId As Integer
    Public Property WeekViewSeriesTypeId As Integer
    Public Property MonthViewSeriesTypeId As Integer
    Public Property SeriesColour As String
    Public Property MeasurementViewGroupId As Integer
    Public Property CalculationFilterId As Integer
    Public Property DayViewDashStyleId As Integer
    Public Property WeekViewDashStyleId As Integer
    Public Property MonthViewDashStyleId As Integer

    Public Overridable Property DayViewSeriesType As MeasurementViewSeriesType
    Public Overridable Property WeekViewSeriesType As MeasurementViewSeriesType
    Public Overridable Property MonthViewSeriesType As MeasurementViewSeriesType
    Public Overridable Property MeasurementViewGroup As MeasurementViewGroup
    Public Overridable Property CalculationFilter As CalculationFilter
    Public Overridable Property DayViewDashStyle As SeriesDashStyle
    Public Overridable Property WeekViewDashStyle As SeriesDashStyle
    Public Overridable Property MonthViewDashStyle As SeriesDashStyle

End Class
