'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MeasurementViewTableType
    Public Property Id As Integer
    Public Property TableTypeName As String

    Public Overridable Property MeasurementViews As ICollection(Of MeasurementView) = New HashSet(Of MeasurementView)

End Class
