'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MeasurementView
    Public Property Id As Integer
    Public Property ViewName As String
    Public Property DisplayName As String
    Public Property TableResultsHeader As String
    Public Property MeasurementTypeId As Integer
    Public Property MeasurementViewTableTypeId As Integer
    Public Property YAxisMinValue As Double
    Public Property YAxisMaxValue As Double
    Public Property YAxisStepValue As Double

    Public Overridable Property MeasurementViewGroups As ICollection(Of MeasurementViewGroup) = New HashSet(Of MeasurementViewGroup)
    Public Overridable Property MeasurementType As MeasurementType
    'Public Overridable Property AllowedUserAccessLevels As ICollection(Of UserAccessLevel) = New HashSet(Of UserAccessLevel)
    Public Overridable Property MeasurementViewTableType As MeasurementViewTableType
    Public Overridable Property ExcludingMeasurementCommentTypes As ICollection(Of MeasurementCommentType) = New HashSet(Of MeasurementCommentType)
    Public Overridable Property Projects As ICollection(Of Project) = New HashSet(Of Project)

End Class
