'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Measurement
    Public Property Id As Integer
    Public Property StartDateTime As Date
    Public Property Duration As Double
    Public Property Level As Double
    Public Property Overload As Nullable(Of Boolean)
    Public Property Underload As Nullable(Of Boolean)
    Public Property MeasurementMetricId As Integer
    Public Property MonitorId As Integer
    Public Property MonitorLocationId As Integer
    Public Property ProjectId As Integer
    Public Property DateTimeUploaded As Date
    Public Property UploadContactId As Integer
    Public Property MeasurementFileId As Integer

    Public Overridable Property MeasurementMetric As MeasurementMetric
    Public Overridable Property Monitor As Monitor
    Public Overridable Property MonitorLocation As MonitorLocation
    Public Overridable Property Project As Project
    Public Overridable Property UploadedByContact As Contact
    Public Overridable Property MeasurementComments As ICollection(Of MeasurementComment) = New HashSet(Of MeasurementComment)
    Public Overridable Property MeasurementFile As MeasurementFile

End Class
