'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MeasurementComment

    Public Property Id As Integer
    Public Property CommentText As String
    Public Property CommentTypeId As Integer
    Public Property CommentDateTime As Date
    Public Property ContactId As Integer
    Public Property MonitorLocationId As Integer
    Public Property FirstMeasurementStartDateTime As Date
    Public Property LastMeasurementEndDateTime As Date

    Public Overridable Property CommentType As MeasurementCommentType
    Public Overridable Property Measurements As ICollection(Of Measurement) = New HashSet(Of Measurement)
    Public Overridable Property Contact As Contact
    Public Overridable Property MonitorLocation As MonitorLocation

End Class
