'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Monitor

    Public Property Id As Integer
    Public Property MonitorName As String
    Public Property MeasurementTypeId As Integer
    Public Property SerialNumber As String
    Public Property Manufacturer As String
    Public Property Model As String
    Public Property Category As String
    Public Property OwnerOrganisationId As Integer
    Public Property RequiresCalibration As Boolean
    Public Property LastFieldCalibration As Nullable(Of Date)
    Public Property LastFullCalibration As Nullable(Of Date)
    Public Property NextFullCalibration As Nullable(Of Date)

    Public Overridable Property MeasurementType As MeasurementType
    Public Overridable Property OwnerOrganisation As Organisation
    Public Overridable Property CurrentLocation As MonitorLocation
    Public Overridable Property DeploymentRecords As ICollection(Of MonitorDeploymentRecord) = New HashSet(Of MonitorDeploymentRecord)
    Public Overridable Property Measurements As ICollection(Of Measurement) = New HashSet(Of Measurement)
    Public Overridable Property Documents As ICollection(Of Document) = New HashSet(Of Document)
    Public Overridable Property MeasurementFiles As ICollection(Of MeasurementFile) = New HashSet(Of MeasurementFile)
    'Public Overridable Property CurrentSettings As MonitorSettings
    Public Overridable Property CurrentStatus As MonitorStatus

End Class
