'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations.Schema

Partial Public Class MonitorDeploymentRecord

    <DatabaseGenerated(DatabaseGeneratedOption.None)> _
    Public Property Id As Integer
    Public Property MonitorId As Integer
    Public Property MonitorLocationId As Integer
    Public Property DeploymentStartDate As Nullable(Of Date)
    Public Property DeploymentEndDate As Nullable(Of Date)

    Public Overridable Property Monitor As Monitor
    Public Overridable Property MonitorLocation As MonitorLocation
    Public Overridable Property MonitorSettings As MonitorSettings

End Class
