'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations.Schema

Partial Public Class MonitorSettings

    <DatabaseGenerated(DatabaseGeneratedOption.None)> _
    Public Property Id As Integer
    Public Property MeasurementPeriod As Double
    Public Property AdditionalInfo1 As String
    Public Property AdditionalInfo2 As String

    'Public Overridable Property Monitor As Monitor
    Public Overridable Property DeploymentRecord As MonitorDeploymentRecord
    Public Overridable Property AirQualitySetting As AirQualitySetting
    Public Overridable Property NoiseSetting As NoiseSetting
    Public Overridable Property VibrationSetting As VibrationSetting

End Class
