'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class MonitorStatus
    Public Property Id As Integer
    Public Property IsOnline As Boolean
    Public Property PowerStatusOk As Boolean
    Public Property StatusComment As String

    <Required()> _
    Public Overridable Property Monitor As Monitor

End Class
