'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PublicHoliday
    Public Property Id As Integer
    Public Property HolidayDate As Date
    Public Property HolidayName As String
    Public Property CountryId As Integer

    Public Overridable Property Country As Country

End Class
