'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class UserAccessLevel

    Public Property Id As Integer
    Public Property AccessLevelName As String

    Public Property ProjectPermissionId As Integer
    <Required()> _
    Public Property ProjectPermission As ProjectPermission

    ' Assessment Criteria
    Public Property CanCreateAssessmentCriteria As Boolean
    Public Property CanEditAssessmentCriteria As Boolean
    Public Property CanViewAssessmentCriteria As Boolean
    Public Property CanDeleteAssessmentCriteria As Boolean


    ' Assessments
    Public Property CanViewAssessments As Boolean

    ' Calculation Filters
    Public Property CanCreateCalculationFilters As Boolean
    Public Property CanViewCalculationFilterList As Boolean
    Public Property CanViewCalculationFilterDetails As Boolean
    Public Property CanEditCalculationFilters As Boolean
    Public Property CanDeleteCalculationFilters As Boolean

    ' Contacts
    Public Property CanCreateContacts As Boolean
    Public Property CanViewContactList As Boolean
    Public Property CanViewContactDetails As Boolean
    Public Property CanEditContacts As Boolean
    Public Property CanDeleteContacts As Boolean

    ' Countries
    Public Property CanCreateCountries As Boolean
    Public Property CanViewCountryList As Boolean
    Public Property CanViewCountryDetails As Boolean
    Public Property CanEditCountries As Boolean
    Public Property CanDeleteCountries As Boolean

    ' Documents
    Public Property CanViewDocumentDetails As Boolean
    Public Property CanViewDocumentList As Boolean
    Public Property CanCreateDocuments As Boolean
    Public Property CanEditDocuments As Boolean
    Public Property CanDeleteDocuments As Boolean

    ' Document Types
    Public Property CanViewDocumentTypeList As Boolean
    Public Property CanViewDocumentTypeDetails As Boolean
    Public Property CanEditDocumentTypes As Boolean
    Public Property CanDeleteDocumentTypes As Boolean
    Public Property CanCreateDocumentTypes As Boolean

    ' Measurements
    Public Property CanViewMeasurements As Boolean
    Public Property CanUploadMeasurements As Boolean
    Public Property CanDeleteMeasurements As Boolean

    ' Measurement Comments
    Public Property CanViewMeasurementCommentList As Boolean
    Public Property CanDeleteMeasurementComments As Boolean
    Public Property CanCreateMeasurementComments As Boolean

    ' Measurement Comment Types
    Public Property CanViewMeasurementCommentTypeList As Boolean
    Public Property CanViewMeasurementCommentTypeDetails As Boolean
    Public Property CanCreateMeasurementCommentTypes As Boolean
    Public Property CanEditMeasurementCommentTypes As Boolean
    Public Property CanDeleteMeasurementCommentTypes As Boolean

    ' Measurement Files
    Public Property CanViewMeasurementFileDetails As Boolean
    Public Property CanViewMeasurementFileList As Boolean
    Public Property CanDeleteMeasurementFiles As Boolean

    ' Measurement Metrics
    Public Property CanCreateMeasurementMetrics As Boolean
    Public Property CanViewMeasurementMetricList As Boolean
    Public Property CanViewMeasurementMetricDetails As Boolean
    Public Property CanEditMeasurementMetrics As Boolean
    Public Property CanDeleteMeasurementMetrics As Boolean

    ' Measurement Views
    Public Property CanViewMeasurementViewList As Boolean
    Public Property CanViewMeasurementViewDetails As Boolean
    Public Property CanCreateMeasurementViews As Boolean
    Public Property CanEditMeasurementViews As Boolean
    Public Property CanDeleteMeasurementViews As Boolean

    ' Monitors
    Public Property CanViewMonitorDetails As Boolean
    Public Property CanViewMonitorList As Boolean
    Public Property CanCreateMonitors As Boolean
    Public Property CanDeleteMonitors As Boolean
    Public Property CanEditMonitors As Boolean

    ' Monitor Deployment Records
    Public Property CanViewMonitorDeploymentRecordList As Boolean
    Public Property CanDeleteMonitorDeploymentRecords As Boolean
    Public Property CanViewMonitorDeploymentRecordDetails As Boolean
    Public Property CanCreateDeploymentRecords As Boolean
    Public Property CanEndMonitorDeployments As Boolean

    ' Monitor Locations
    Public Property CanViewMonitorLocationDetails As Boolean
    Public Property CanViewMonitorLocationList As Boolean
    Public Property CanDeleteMonitorLocations As Boolean
    Public Property CanViewSelectMonitorLocations As Boolean
    Public Property CanEditMonitorLocations As Boolean
    Public Property CanCreateMonitorLocations As Boolean

    ' Organisations
    Public Property CanEditOrganisations As Boolean
    Public Property CanViewOrganisationDetails As Boolean
    Public Property CanViewOrganisationList As Boolean
    Public Property CanCreateOrganisations As Boolean
    Public Property CanDeleteOrganisations As Boolean

    ' Organisation Types
    Public Property CanCreateOrganisationTypes As Boolean
    Public Property CanDeleteOrganisationTypes As Boolean
    Public Property CanEditOrganisationTypes As Boolean
    Public Property CanViewOrganisationTypeList As Boolean
    Public Property CanViewOrganisationTypeDetails As Boolean

    ' Projects
    Public Property CanCreateProjects As Boolean
    Public Property CanDeleteProjects As Boolean
    Public Property CanEditProjects As Boolean
    Public Property CanViewProjectDetails As Boolean
    Public Property CanViewProjectList As Boolean


    ' Public Holidays
    Public Property CanCreatePublicHolidays As Boolean
    Public Property CanDeletePublicHolidays As Boolean

    ' System Messages
    Public Property CanCreateSystemMessages As Boolean
    Public Property CanDeleteSystemMessages As Boolean
    Public Property CanEditSystemMessages As Boolean
    Public Property CanViewSystemMessages As Boolean

    ' Users
    Public Property CanCreateUsers As Boolean
    Public Property CanDeleteUsers As Boolean
    Public Property CanEditUsers As Boolean
    Public Property CanViewUserDetails As Boolean
    Public Property CanViewUserList As Boolean
    Public Property CanInitiatePasswordResets As Boolean

    ' User Access Levels
    Public Property CanCreateUserAccessLevels As Boolean
    Public Property CanDeleteUserAccessLevels As Boolean
    Public Property CanEditUserAccessLevels As Boolean
    Public Property CanViewUserAccessLevelDetails As Boolean
    Public Property CanViewUserAccessLevelList As Boolean

    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)

    ' TODO: Legacy (work out how to get rid of this) 
    Public Overridable Property Contacts As ICollection(Of Contact) = New HashSet(Of Contact)


End Class
