'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations
Imports System.ComponentModel.DataAnnotations.Schema

Partial Public Class VibrationSetting

    <DatabaseGenerated(DatabaseGeneratedOption.None)> _
    Public Property Id As Integer
    Public Property AlarmTriggerLevel As String
    Public Property XChannelWeighting As String
    Public Property YChannelWeighting As String
    Public Property ZChannelWeighting As String

    <Required()> _
    Public Overridable Property MonitorSettings As MonitorSettings

End Class
